# fly.toml app configuration file generated for go-gym-track-api on 2026-08-23T19:39:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-gym-track-api'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = '/migrate'

[env]
  ACCESS_TOKEN_TTL = '15m'
  APP_ENV = 'production'
  COOKIE_SECURE = 'true'
  JWT_AUDIENCE = 'go-gym-track-api'
  JWT_ISSUER = 'go-gym-track'
  PORT = '10000'
  REFRESH_TOKEN_TTL = '720h'
  RUN_MIGRATIONS = 'false'

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
